apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bulr8rg7g-nodejs 
  janus-idp.io/tekton: bulr8rg7g-nodejs
  backstage.io/kubernetes-id: bulr8rg7g-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bulr8rg7g-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  